### ISSUE TITLE
Unable to start Whapa because of tkinter module on Linux Mint 19.2 (Tina) MATE

### ISSUE THREAD

**Issue by KaMyKaSii** [B16f00t/whapa#37] opened 2019-11-08 20:18 UTC
```
matheus@matheus-CL341:~/Downloads/Persepolis/Compressed/whapa-master$ pip3 install -r ./doc/requirements.txt
Collecting pycryptodome (from -r ./doc/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/41/43/1598eb29a97cfbeb370f09936c64add9109a764acf30fd3ff876b5d3f8ed/pycryptodome-3.9.1-cp36-cp36m-manylinux1_x86_64.whl (9.7MB)
    100% |████████████████████████████████| 9.7MB 67kB/s 
Collecting colorama (from -r ./doc/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting configparser (from -r ./doc/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Collecting gpsoauth (from -r ./doc/requirements.txt (line 4))
Collecting pycryptodomex>=3.0 (from gpsoauth->-r ./doc/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/d1/b9/4583d5b6a15a8213d21f24f0d1faa71951b64555b4860612df8eef696d24/pycryptodomex-3.9.1-cp36-cp36m-manylinux1_x86_64.whl (9.7MB)
    100% |████████████████████████████████| 9.7MB 63kB/s 
Collecting requests (from gpsoauth->-r ./doc/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->gpsoauth->-r ./doc/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->gpsoauth->-r ./doc/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->gpsoauth->-r ./doc/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->gpsoauth->-r ./doc/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
Installing collected packages: pycryptodome, colorama, configparser, pycryptodomex, chardet, idna, certifi, urllib3, requests, gpsoauth
Successfully installed certifi-2019.9.11 chardet-3.0.4 colorama-0.4.1 configparser-4.0.2 gpsoauth-0.4.1 idna-2.8 pycryptodome-3.9.1 pycryptodomex-3.9.1 requests-2.22.0 urllib3-1.25.6
matheus@matheus-CL341:~/Downloads/Persepolis/Compressed/whapa-master$ python3 whapa-gui.py
Traceback (most recent call last):
  File "whapa-gui.py", line 5, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'
matheus@matheus-CL341:~/Downloads/Persepolis/Compressed/whapa-master$ pip3 install tkinter
Collecting tkinter
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/tkinter/
matheus@matheus-CL341:~/Downloads/Persepolis/Compressed/whapa-master$ 
```

**Comment by B16f00t** [comment] 2019-11-08 23:07
Duplicate of #33

**Closed by B16f00t** 2019-11-08 23:07 UTC
